from list_search import add_search
from html import escape as E
BASE=""
cats={'gem':('GEM','Grupo de Ensino Musical','Fundamentos, leitura e prática para aprender em conjunto.'),'artigos':('Artigos','Tudo sobre música','Ideias e ferramentas para a música na orquestra e em casa.'),'doar':('Doações','Apoie o Clave Sol','Instrumentos, materiais e outras formas de contribuir com a música.'),'luthier':('Luthier','Serviços de luthier','O cuidado com o instrumento também faz parte da música.'),'links':('Links','Aplicativos musicais','Ferramentas para escrever, ouvir e compreender o som.'),'tutoriais':('Tutoriais','Dicas e técnicas','Um passo de cada vez. Mais confiança a cada ensaio.')}
def page(title,body,base):
 body=add_search(body,base)
 global BASE
 BASE=base
 nav=''.join(f'<a href="https://clavesol.com.br/{k}/">{v[0]}</a>' for k,v in cats.items())
 return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Clave Sol: partituras, ensino musical, artigos, luthier e aplicativos para a orquestra e para casa."><meta name="theme-color" content="#123b35"><title>{E(title)} · Clave Sol</title><link rel="icon" href="{BASE}/assets/icon.svg"><link rel="stylesheet" href="{BASE}/assets/style.css"></head><body><a class="skip" href="#conteudo">Pular para o conteúdo</a><div class="topline">MÚSICA PARA APRENDER, PRATICAR E COMPARTILHAR</div><header><a class="brand" href="https://clavesol.com.br/"><img class="brand-logo" src="{BASE}/assets/logo-clavesol.webp" alt="" width="70" height="80"><span>Clave Sol<small>UM ENCONTRO COM A MÚSICA</small></span></a><nav aria-label="Principal">{nav}<a class="nav-score" href="https://clavesol.com.br/partituras/">Partituras</a></nav></header><main id="conteudo">{body}</main><footer><a class="brand" href="https://clavesol.com.br/"><img class="brand-logo" src="{BASE}/assets/logo-clavesol.webp" alt="" width="70" height="80"><span>Clave Sol<small>APRENDER. TOCAR. COMPARTILHAR.</small></span></a><p>Da primeira nota ao próximo ensaio.<br>Um espaço musical de Djames Suhanko.</p><a class="social-link" href="https://www.youtube.com/@ClaveSolMusic"><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" focusable="false"><rect x="1" y="4" width="22" height="16" rx="5" fill="currentColor"/><path d="M10 8l6 4-6 4z" fill="var(--paper)"/></svg><span>Clave Sol Music<small>Nosso canal no YouTube</small></span></a></footer><script defer src="{BASE}/assets/updates.js" data-version="__CLAVESOL_VERSION__" data-manifest="{BASE}/version.json"></script></body></html>'''
